spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_customer
    username: postgres
    password: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8090
