
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_notification
    username: postgres
    password: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.deva.ecommerce.kafka.order.OrderConfirmation,PaymentNotificationRequest:com.deva.ecommerce.notification.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: devaraj
    password: devaraj
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8094

