spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_order
    username: postgres
    password: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8092
application:
  config:
    customer-url: http://localhost:8090/api/v1/customer
    payment-url: http://localhost:8093/api/v1/payments
    product-url: http://localhost:8091/api/v1/products


