
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_product
    username: postgres
    password: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  port: 8091

