
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_notification
    username: postgres
    password: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8094

